changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Updates
      labels:
        - enhancement
        - refactor
    - title: Deprecations
      labels:
        - deprecation
    - title: Fixes
      labels:
        - "*"
