# This workflow will do a clean install of node dependencies, cache/restore them,
# build the source code and run tests

# source: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js 22.0.0
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '22.0.0'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn prepublishOnly
      - run: node index.node.js
      - run: yarn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn check-deps
