# This workflow will do a clean install of node dependencies, cache/restore them, 
# build the source code and run tests

# source: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.3.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.3.0'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build:node
    - run: node index.node.js
    - run: yarn build
    - run: yarn test
    - run: yarn check-deps