name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20.10.0'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          rm -rf node_modules && rm -rf ./react-example/node_modules
          yarn install --frozen-lockfile && yarn --cwd ./react-example install --frozen-lockfile
      - name: Start React Sample App
        run: yarn start:all:react-start-without-watch
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
