name: publish
on:
  release:
    types:
      - published

jobs:
  publish:
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use Node.js 22
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm for OIDC support
        run: npm install -g npm@latest
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: yarn build:node
      - name: Publish to npm
        run: npm publish --provenance
